# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'WDPodTest' do
  
#pod 'WDPodspecDemo' '0.0.4'
    pod 'AFNetworking'
#pod 'WDPodspecDemo',:git=>'https://cocoapods.org/pods/WDPodspecDemo'
pod 'WDPodspecDemo',:git=>'https://github.com/weidongjiang/WDPodspecDemo.git'

end
